import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


file_path = 'wl-2021.csv'
df = pd.read_csv(file_path)

print(df.head())

print(df.describe(include='all'))

print(df.info())

print("Column Names:")
print(df.columns)



df.columns = ['Waste Type', 'Total Generated (000 tonnes)', 'Total Recycled (000 tonnes)']


plt.figure(figsize=(10, 6))


plt.figure()
sns.barplot(x='Waste Type', y='Total Generated (000 tonnes)', data=df, palette='viridis')
plt.title('Total Waste Generated by Type (2021)')
plt.ylabel('Total Generated (000 tonnes)')
plt.xlabel('Waste Type')
plt.xticks(rotation=45, ha='right')  
plt.tight_layout()
plt.show()


plt.figure()
sns.barplot(x='Waste Type', y='Total Recycled (000 tonnes)', data=df, palette='viridis')
plt.title('Total Waste Recycled by Type (2021)')
plt.ylabel('Total Recycled (000 tonnes)')
plt.xlabel('Waste Type')
plt.xticks(rotation=45, ha='right') 
plt.tight_layout()
plt.show()

plt.figure()
df_melted = df.melt(id_vars=['Waste Type'], value_vars=['Total Generated (000 tonnes)', 'Total Recycled (000 tonnes)'], 
                    var_name='Type', value_name='Amount (000 tonnes)')
sns.barplot(x='Waste Type', y='Amount (000 tonnes)', hue='Type', data=df_melted, palette='viridis')
plt.title('Total Generated vs. Total Recycled by Waste Type (2021)')
plt.ylabel('Amount (000 tonnes)')
plt.xlabel('Waste Type')
plt.xticks(rotation=45, ha='right')  
plt.tight_layout()
plt.show()
